stages:
  # --- STAGE 0: COMMON BASE (Deduplication) ---
  # Rimuove i duplicati mantenendo la struttura train/val/test
  deduplicate:
    cmd: python src/preprocessing/deduplicate.py --input data/raw --output data/deduplicated
    deps:
      - data/raw
      - src/preprocessing/deduplicate.py
    outs:
      - data/deduplicated
