stages:
  # =======================================================
  # PIPELINE 2: DATA AUGMENTATION
  # =======================================================

  # 1. Augmentation
  augment:
    wdir: ../../
    cmd: python -m src.preprocessing.augment --input data/deduplicated/train --output data/augmented/train
    deps:
      - data/deduplicated/train
      - src/preprocessing/augment.py
    outs:
      - data/augmented/train

  # 2. Training (su dati aumentati)
  train:
    foreach: [effnet_v2_s, convnext]
    do:
      wdir: ../../
      cmd: >
        python -m src.training.train 
        --model ${item} 
        --train data/augmented/train 
        --val data/deduplicated/valid 
        --out pipelines/p2_augmented/results/${item} 
        --batch 16 
        --epochs 4
      deps:
        - data/augmented/train
        - data/deduplicated/valid
        - src/training/train.py
      outs:
        - pipelines/p2_augmented/results/${item}/model.pth
        - pipelines/p2_augmented/results/${item}/loss_plot.png
        - pipelines/p2_augmented/results/${item}/history.json

  # 3. Evaluation
  evaluate:
    foreach: [effnet_v2_s, convnext]
    do:
      wdir: ../../
      # Prende i pesi appena creati in results/
      cmd: >
        python -m src.training.evaluate 
        --model ${item} 
        --weights pipelines/p2_augmented/results/${item}/model.pth 
        --data data/deduplicated/test 
        --out pipelines/p2_augmented/results/${item}
      deps:
        - data/deduplicated/test
        - src/training/evaluate.py
        - pipelines/p2_augmented/results/${item}/model.pth
      metrics:
        - pipelines/p2_augmented/results/${item}/metrics.json:
            cache: false
      plots:
        - pipelines/p2_augmented/results/${item}/confusion_matrix.png:
            cache: false
        - pipelines/p2_augmented/results/${item}/classification_report.png:
            cache: false