stages:
  # =======================================================
  # PIPELINE 3: BALANCING (Two-Phase Learning)
  # =======================================================

  # 1. Creazione Dataset Bilanciato
  balance:
    wdir: ../../
    cmd: python -m src.preprocessing.balance --input data/deduplicated/train --output data/balanced/train
    deps:
      - data/deduplicated/train
      - src/preprocessing/balance.py
    outs:
      - data/balanced/train

  # 2. FASE 1: Training su Dataset BILANCIATO
  train_phase1:
    foreach: [effnet_v2_s, convnext]
    do:
      wdir: ../../
      cmd: >
        python -m src.training.train 
        --model ${item} 
        --train data/balanced/train 
        --val data/deduplicated/valid 
        --out pipelines/p3_two_phase/results/phase1/${item} 
        --batch 16 
        --epochs 4
      deps:
        - data/balanced/train
        - data/deduplicated/valid
        - src/training/train.py
      outs:
        - pipelines/p3_two_phase/results/phase1/${item}/model.pth
        - pipelines/p3_two_phase/results/phase1/${item}/loss_plot.png

  # 3. FASE 2: Fine-Tuning su Dataset ORIGINALE
  train_phase2:
    foreach: [effnet_v2_s, convnext]
    do:
      wdir: ../../
      cmd: >
        python -m src.training.train 
        --model ${item} 
        --train data/deduplicated/train 
        --val data/deduplicated/valid 
        --out pipelines/p3_two_phase/results/phase2/${item} 
        --weights pipelines/p3_two_phase/results/phase1/${item}/model.pth
        --batch 16 
        --epochs 4
      deps:
        - data/deduplicated/train
        - data/deduplicated/valid
        - src/training/train.py
        - pipelines/p3_two_phase/results/phase1/${item}/model.pth
      outs:
        - pipelines/p3_two_phase/results/phase2/${item}/model.pth
        - pipelines/p3_two_phase/results/phase2/${item}/loss_plot.png
        - pipelines/p3_two_phase/results/phase2/${item}/history.json

  # 4. Valutazione Finale (Sul modello Fase 2)
  evaluate:
    foreach: [effnet_v2_s, convnext]
    do:
      wdir: ../../
      cmd: >
        python -m src.training.evaluate 
        --model ${item} 
        --weights pipelines/p3_two_phase/results/phase2/${item}/model.pth 
        --data data/deduplicated/test 
        --out pipelines/p3_two_phase/results/phase2/${item}
      deps:
        - data/deduplicated/test
        - src/training/evaluate.py
        - pipelines/p3_two_phase/results/phase2/${item}/model.pth
      metrics:
        - pipelines/p3_two_phase/results/phase2/${item}/metrics.json:
            cache: false
      plots:
        - pipelines/p3_two_phase/results/phase2/${item}/confusion_matrix.png:
            cache: false
        - pipelines/p3_two_phase/results/phase2/${item}/classification_report.png:
            cache: false